### ISSUE TITLE
values injected into path should always contain at least a single character

### ISSUE THREAD

**Issue by marstr** [Azure/openapi-validation-tools#77]
As seen in issue Azure/azure-sdk-for-go#576, passing an empty string as a variable which will be injected into the operation path can change the semantics of a request. This leads to unmarshalling failure.

A validator rule which ensures that any variable present in the path have a [minimum length](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.2) of 1 would ensure this issue doesn't pop up again.

**Comment by vishrutshah** [comment]
@marstr Is this supposed to be an linter rule or Model validator rule?

**Comment by marstr** [comment]
Hmmm, well that's a good question. I assume that like we see in the bug mentioned above, not adhering to this can break queries. In that way, I would put it in the Model validator. However, I'm totally willing to believe there is an edge case I don't know about with swagger where it could be necessary to allow for a 0-length argument in the path. If such an edge case exists, I would make this a linter rule.

**Comment by vishrutshah** [comment]
We believe that swagger must be swagger must be modeled more sticker using `minLength` & `maxLength` so that we can validate them otherwise "empty string" will be a valid input for model validator. 

We can have linter rule that warns "If you have parameter in path of type string then please add minLength: 1". 

@marstr can you please open a bung in autorest with linter tag.

**Comment by marstr** [comment]
Sure thing.
